import express from "express";
import cors from "cors";
import helmet from "helmet";
import { apiLimiter, authLimiter } from "./middleware/rateLimit.js";
import swaggerUi from "swagger-ui-express";
import { connectDB } from "./config/db.js";
import { swaggerSpec } from "./config/swagger.js";
import { errorHandler } from "./middleware/errorHandler.js";
import authRoutes from "./routes/auth.js";
import userRoutes from "./routes/users.js";
import projectRoutes from "./routes/projects.js";
import sprintRoutes from "./routes/sprints.js";
import taskRoutes from "./routes/tasks.js";
import dashboardRoutes from "./routes/dashboard.js";
import notificationRoutes from "./routes/notifications.js";
import uploadRoutes from "./routes/upload.js";
import searchRoutes from "./routes/search.js";
import analyticsRoutes from "./routes/analytics.js";
import adminRoutes from "./routes/admin.js";
import activityRoutes from "./routes/activity.js";
import aiRoutes from "./routes/ai.js";
import workspaceRoutes from "./routes/workspaces.js";
import integrationRoutes from "./routes/integrations.js";
import timeRoutes from "./routes/time.js";
import documentRoutes from "./routes/documents.js";
import epicRoutes from "./routes/epics.js";
import milestoneRoutes from "./routes/milestones.js";
import auditLogRoutes from "./routes/auditLog.js";
import whiteboardRoutes from "./routes/whiteboard.js";
import teamsRoutes from "./modules/teams/index.js";
import meetingsRoutes from "./modules/meetings/index.js";
import chatRoutes from "./modules/chat/index.js";
import gitRoutes from "./modules/git-integrations/index.js";
import cicdRoutes from "./modules/cicd/index.js";
import aiAgentsRoutes from "./modules/ai-agents/index.js";
import knowledgeBaseRoutes from "./modules/knowledge-base/index.js";
import resourcePlanningRoutes from "./modules/resource-planning/index.js";
import roadmapsRoutes from "./modules/roadmaps/index.js";
import reportingRoutes from "./modules/reporting/index.js";
import marketplaceRoutes from "./modules/marketplace/index.js";
import mlopsRoutes from "./modules/mlops/index.js";
import automationModuleRoutes from "./modules/automation/index.js";
import keycloakRoutes from "./routes/keycloak.js";
import caldavRoutes from "./routes/caldav.js";
import emailRoutes from "./routes/email.js";
import storageRoutes from "./routes/storage.js";
import billingRoutes from "./routes/billing.js";
import metricsRoutes from "./routes/metrics.js";
import proposalRoutes from "./routes/proposals.js";
import storyRoutes from "./routes/story.js";
import automationRoutes from "./routes/automation.js";
import predictiveRoutes from "./routes/predictive.js";
import graphRoutes from "./routes/graph.js";
import issueLinksRoutes from "./routes/issueLinks.js";
import issuesRoutes from "./routes/issues.js";
import templatesRoutes from "./routes/templates.js";



const app = express();

app.use(helmet());
app.use(cors());
app.use(apiLimiter);
app.use(express.json({ limit: "10mb" }));

app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.get("/api-docs.json", (req, res) => res.json(swaggerSpec));
app.use("/api/auth", authLimiter, authRoutes);
app.use("/api/users", userRoutes);
app.use("/api/projects", projectRoutes);
app.use("/api/sprints", sprintRoutes);
app.use("/api/tasks", taskRoutes);
app.use("/api/dashboard", dashboardRoutes);
app.use("/api/notifications", notificationRoutes);
app.use("/api/upload", uploadRoutes);
app.use("/api/search", searchRoutes);
app.use("/api/analytics", analyticsRoutes);
app.use("/api/admin", adminRoutes);
app.use("/api/activity", activityRoutes);
app.use("/api/ai", aiRoutes);
app.use("/api/workspaces", workspaceRoutes);
app.use("/api/integrations", integrationRoutes);
app.use("/api/time", timeRoutes);
app.use("/api/documents", documentRoutes);
app.use("/api/epics", epicRoutes);
app.use("/api/milestones", milestoneRoutes);
app.use("/api/teams", teamsRoutes);
app.use("/api/meetings", meetingsRoutes);
app.use("/api/chat", chatRoutes);
app.use("/api/git", gitRoutes);
app.use("/api/cicd", cicdRoutes);
app.use("/api/ai-agents", aiAgentsRoutes);
app.use("/api/knowledge-base", knowledgeBaseRoutes);
app.use("/api/resource-planning", resourcePlanningRoutes);
app.use("/api/roadmaps", roadmapsRoutes);
app.use("/api/reporting", reportingRoutes);
app.use("/api/marketplace", marketplaceRoutes);
app.use("/api/mlops", mlopsRoutes);
app.use("/api/automation", automationModuleRoutes);
app.use("/api/auth/keycloak", keycloakRoutes);
app.use("/api/caldav", caldavRoutes);
app.use("/api/email", emailRoutes);
app.use("/api/storage", storageRoutes);
app.use("/api/billing", billingRoutes);
app.use("/api/metrics", metricsRoutes);
app.use("/api/proposals", proposalRoutes);
app.use("/api/story", storyRoutes);
app.use("/api/automation", automationRoutes);
app.use("/api/predictive", predictiveRoutes);
app.use("/api/graph", graphRoutes);
app.use("/api/issue-links", issueLinksRoutes);
app.use("/api/issues", issuesRoutes);
app.use("/api/templates", templatesRoutes);


import riskRoutes from "./routes/risk.js";
app.use("/api/risk", riskRoutes);
app.use("/api/whiteboards", whiteboardRoutes);
app.get("/health", (req, res) => res.json({ ok: true }));
app.use(errorHandler);

export { app, connectDB };
